name: environment
channels:
  - conda-forge
  - pip
dependencies:
  - gdal
  - glob
  - h5py
  - imageio
  - numpy
  - osgeo
  - pandas
  - plotly
  - pylab
  - rasterio
  - rioaxarray
  - shutil
  - wget
