name: environment
channels:
  - conda-forge
  - defaults
dependencies:
- python>=3.6
- pandas
- gdal>=2.4
- numpy
- rioxarray
- rasterio
- leafmap
- wget
- matplotlib
- h5py
- imageio
- plotly
