name: snowtoday

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - gdal
  - h5py
  - leafmap
  - imageio
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - plotly
  - rasterio
  - rioxarray
  - wget
  - xarray
