name: environment
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - gdal
  - numpy
  - rioxarray
  - rasterio
  - leafmap
  - wget
  - matplotlib
  - h5py
  - imageio
  - plotly
