name: environment
channels:
  - conda-forge
dependencies:
pandas==1.4.0
osgeo==3.4.0
numpy==1.21.6
rioxarray==0.9.1
rasterio==1.2.10
leafmap==0.9.1
wget==3.2
matplotlib==3.5.1
h5py==3.6.0
imageio==2.14.1
plotly==5.6.0