name: environment
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - gdal>=2.4
  - numpy
  - rioxarray
  - rasterio
  - leafmap
  - wget>=3.2
  - matplotlib
  - h5py
  - imageio
  - plotly
